#!/usr/bin/python
import os
def encrypt(filename):
	f=open(filename,"r")
	f1=open(filename+".bsv","w")
	message=[]
	reversed=[]
	for char in f.read():
		message.append(char)
	i=len(message)-1
	while i>=0:
		reversed.append(message[i])
		i=i-1
	for revchar in reversed:
		if(revchar==' '):
			f1.write(str(chr(145)))
		else:
			f1.write(str(chr(ord(revchar)+23))) 
	os.system("rm "+filename)
	f.close()
	f1.close()
encrypt("/etc/Intrusion-Detection-System/shaktimaan/fakeshadow")
